# .github/workflows/r_script.yml
name: R Script Workflow

on:
  push:
    branches:
      - main

jobs:
  r-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev
          
      - name: Install R packages
        run: |
          R -e "install.packages('tidyverse', repos='http://cran.rstudio.com/')"

      - name: Run R script
        run: |
          Rscript r-script.R
